version: '3.8'

services:
  postgres-order:
    image: postgres:16
    container_name: postgres-order
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: ${ORDER_DB_USER:-order_user}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD:-order_password}
    ports:
      - "5434:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - sec-network

volumes:
  postgres_order_data:

networks:
  sec-network:
    external: true
