version: '3.8'

services:
  postgres-profile:
    image: postgres:16
    container_name: postgres-profile
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: ${PROFILE_DB_USER:-profile_user}
      POSTGRES_PASSWORD: ${PROFILE_DB_PASSWORD:-profile_password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_profile_data:/var/lib/postgresql/data
    networks:
      - sec-network

volumes:
  postgres_profile_data:

networks:
  sec-network:
    external: true
